### ISSUE TITLE
Make exclude_from_nav not required

### ISSUE THREAD

**Issue by gweis** [plone/plone.app.dexterity#101]
Hi,

As exclude_from_nav has a default value set, it is probably not necessary to set this field to required.

Any opinions?

**Comment by jaroel** [comment]
I think that somewhere in Plone exclude_from_nav is made optional.
We do see exclude_from_nav as required in plone.restapi.

**Comment by jaroel** [comment]
The @types/Document call returns
```
 "required": [
    "title",
    "exclude_from_nav"
  ],
```

**Comment by jaroel** [comment]
The Archetypes equivalent explicitly sets required=False.
