### ISSUE TITLE
Dynamic schemas and multiple zeoclients

### ISSUE THREAD

**Issue by domruf** [plone/plone.app.dexterity#104]
According to 
https://code.google.com/p/dexterity/issues/detail?id=286
this should be fixed in plone.dexerity >= 2.1.1.

But I use plone.dexterity-2.1.3 and plone.app.dexterity-2.0.8 and still have this problem.
- Fire up a ZEO server and a few clients with a 4.3 buildout.
- Pointing at :8081, make a type and add one field via. schema editor
- Open same editor page on :8082 (the first time this type has been used on this client), all looks same
- Add another field using :8081.
- Refresh editor page on :8082, no sign of extra field.

**Comment by href** [comment]
Did you ever found a work around for this issue? We have the same issue on one of our deployments.

**Comment by jensens** [comment]
invalidation was fixed
