### ISSUE TITLE
Improvement : ability to configure catalogs and having multiple catalogs for a content type

### ISSUE THREAD

**Issue by tdesvenain** [plone/plone.app.dexterity#106]
Hi,

Under Archetypes, it was possible to configure wich catalog tool was used with any content type, and we could set multiple catalogs for a content type.

This would be great to have this with dexterity.

Do you agree ? I can work on this. Is a PLIP needed ?

**Comment by jensens** [comment]
with collective.indexing merged in core and other optimizations this is a really bad idea.
