### ISSUE TITLE
3 bug trackers?

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.dexterity#113]
looks like this bugtracker is the prefered one for dexterity bugs? Also for plone.dexterity?

i also found https://dev.plone.org/query?status=assigned&status=confirmed&status=new&status=reopened&component=Dexterity&type=Bug&col=id&col=summary&col=component&col=status&col=type&col=priority&col=milestone&report=59&order=priority
and theres a link to http://code.google.com/p/dexterity/issues/list

This needs cleanup.

**Comment by jensens** [comment]
for the records: please use the https://github.com/plone/plone.app.dexterity/issues tracker and no other.
trac will die soon anyway.
if someone can give my user jk@kleinundpartner.at permission on the google code page i can place a info text over there.

**Comment by jensens** [comment]
also, in master README the issue tracker now points here.

**Comment by davisagli** [comment]
@jensens you should have access to administer the google code page now; thanks.

**Comment by jensens** [comment]
ok, i places information over there, now rac is left, but the problem will be solved anyway soon, so i close this issue.

**Comment by thet** [comment]
the only drawback with github issue trackers is, that regular plone users can't use it without a github account. there was a discussion some time ago about but tracking in plone: https://community.plone.org/t/bug-tracking-triaging-proposal/183
however: +1 for using github :)
