### ISSUE TITLE
ICategorization(context).subjects vs. context.subject

### ISSUE THREAD

**Issue by thet** [plone/plone.app.dexterity#118]
the ICategorization behavior has a `subjects` (plural) field, which is stored on the `subject` (singular) attribute on the context. This is quite confusing and made me scratch my head for quite some time.
If I recall correctly, this is done because the Dublin Core defines a `Subject` (plural, capitalization) field.
I fear, we need this confusing situation to not break the catalog metadata, CMFCore and whatever API. But isn't there a better way - like providing a `Subject` indexer but storing the attribute on context.subjects?

**Comment by petri** [comment]
I think the goal should be to deprecate "subjects" in favour of "subject" in ICategorization. Simply because "subjects" is not DC metadata and thus our Dexterity DC behavior implementation can be considered broken. Capitalized or not.

**Comment by thet** [comment]
Stale issue.
