### ISSUE TITLE
need docs update for TTW XML editor

### ISSUE THREAD

**Issue by tkimnguyen** [plone/plone.app.dexterity#123]
in reference/dexterity-xml.rst it says "(Dexterity will probably also include a TTW XML-model editor at some point in the future.)" but this TTW model editor now exists.  I could just change it to say that it exists but maybe someone might like to say more about the editor.

**Comment by svx** [comment]
as @polyester said, it has to be changed here not in github.com/plone/documentation. Once it is fixed here the docs will pick it up during the following build

**Comment by smcmahon** [comment]
I've addressed this in a just-submitted pull request.

**Comment by jensens** [comment]
@smcmahon which one? reference is always helpful :)

**Comment by jensens** [comment]
i remove the sentence in #150 i think ttw related docs should go in a different part of the documentation.
