### ISSUE TITLE
Obsolete references to collective.autopermission

### ISSUE THREAD

**Issue by gforcada** [plone/plone.app.dexterity#140]
_(copied from https://github.com/plone/documentation/issues/160)_

I was reading http://docs.plone.org/external/plone.app.dexterity/docs/advanced/permissions.html and saw that it talks about collective.autopermission but it already warns that is merged in Zope, so probably we can remove that for both Plone 4 and Plone 5 documentation and keep it (?) for Plone 3?

Not sure how to keep some docs for one version or another.

**Comment by MrTango** [comment]
What is the status of the updated docs?
Can i help?

**Comment by jensens** [comment]
I am pretty sure this is already fixed.
