### ISSUE TITLE
Broken zip release

### ISSUE THREAD

**Issue by gforcada** [plone/plone.app.dexterity#155]
At WPOD in Berlin @staeff found out that plone.app.dexterity 2.0.12 is **completely broken**.

Download and try to open it by yourself: https://pypi.python.org/pypi/plone.app.dexterity/2.0.12 the file extractor of you OS will give you an error.

@esteele you made that release, maybe there was a connection error while uploading?

**Comment by tisto** [comment]
There is nothing we can do about brown bag releases like this except documenting it. We can not (and should not) re-upload eggs. There is already a more recent working release.

**Comment by gforcada** [comment]
Really? we can not re-upload eggs? But then we have people that their buildouts are failing due to that, of course they can pin to a newer/older version, but if for whichever reason they could not, they will have to make their own private egg...

**Comment by tisto** [comment]
pypi does not allow to remove or re-upload eggs because people used that in the past to remove releases (which is far worse than having brown-bag releases).

**Comment by gforcada** [comment]
Aha, I see: http://comments.gmane.org/gmane.comp.python.distutils.devel/22739

Then we need to make sure everyone is aware of that.

**Comment by esteele** [comment]
Pypi has a bad habit of hanging up during uploads. That, combined with 
the new no-changing-files rule makes for bad releases. I didn't catch 
that one or I'd have fixed it. Sorry.

**Comment by mauritsvanrees** [comment]
For the record, I can unzip the 2.0.12 file just fine on my Mac and on a Linux server.
