### ISSUE TITLE
Commits when opening edit form

### ISSUE THREAD

**Issue by ralphjacobs** [plone/plone.app.dexterity#173]
It seems that dexterity commits to the zodb when opening an edit form (using an custom contenttype).
I've used these patches when working on performance on website: https://gist.github.com/malthe/2895420

Then i came across this when debugging.

Customizing the edit form using this seems to prevent this. For example:

```
 <browser:page
   for="test.example.interfaces.IMyType"
   name="edit"
   class="test.example.content.mytype.EditForm"
   permission="cmf.ModifyPortalContent"
   />
```

from plone.dexterity.browser import edit

```
class EditForm(edit.DefaultEditForm):
    portal_type = "mytype"

    def update(self):
        super(edit.DefaultEditForm, self).update()
```

~
ralph

**Comment by jensens** [comment]
Idea: I it the "locking" feature which writes?
