### ISSUE TITLE
Custom add forms documentation faulty?

### ISSUE THREAD

**Issue by reinhardt** [plone/plone.app.dexterity#181]
I was trying to create a custom add form as described here:

https://github.com/plone/plone.app.dexterity/blob/master/docs/advanced/custom-add-and-edit-forms.rst#custom-add-forms

I got a 404 for the ++add++ page, and going in with the debugger showed that this error was the cause:

```AttributeError: "'AddForm' object has no attribute '__of__'"```

I dug a bit and what worked in the end was doing it like this:

```
from plone.dexterity.browser import add

class AddForm(add.DefaultAddForm):
    portal_type = 'example.fspage'

class AddView(add.DefaultAddView):
    form = AddForm
```

and then using AddView instead of AddForm in the ZCML.

Is the documentation wrong or am I missing something here?

**Comment by jensens** [comment]
looks like the documentation is wrong here.

**Comment by reinhardt** [comment]
Thanks for your assessment! I've created a pull request: #194
