### ISSUE TITLE
Docs: incorrect description of static vocabularies

### ISSUE THREAD

**Issue by fulv** [plone/plone.app.dexterity#198]
In [the docs for dynamic vocabulary sources](http://docs.plone.org/external/plone.app.dexterity/docs/advanced/vocabularies.html#dynamic-sources) the second sentence in this paragraph seems to me to be incorrect:

> The static vocabulary is obviously a bit limited. Not only is it hard-coded in Python, it also does not allow separation of the stored values and the labels shown in the selection widget.

Using the example from the section on Static Vocabularies, if I change one value (here _value:_ Jimbo, _title_: Bill), I get a separation in the produced html:

```
organizers = SimpleVocabulary(
    [SimpleTerm(value=u'Jimbo', title=_(u'Bill')),
     SimpleTerm(value=u'Bob', title=_(u'Bob')),
     SimpleTerm(value=u'Jim', title=_(u'Jim'))]
    )
```

Here is the html that results:

```
<select blahblah>
        <option value="Jimbo">Bill</option>
        <option value="Bob">Bob</option>
        <option value="Jim">Jim</option>
      </select>
```

So unless I'm misunderstanding it, the sentence _it also does not allow separation of the stored values and the labels shown in the selection widget_ needs to be removed.

**Comment by davisagli** [comment]
I agree
