### ISSUE TITLE
Is actions.xml still needed?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.dexterity#218]
Our `actions.xml` registers `dexterity-types` as controlpanel item. But this is what `controlpanel.xml` is for. But @davisagli added this seven years ago in 4d9c4791b1c65f2de0c1a992d1a415a9023e3635 when `controlpanel.xml` was already there.
Am I missing something? Everything seems fine when I remove this on Plone 5.1. This is the only action in the `controlpanel` category of `portal_actions`.
I guess it can be removed.

**Comment by davisagli** [comment]
Fine to remove. Probably left over from when we were thinking we would replace the control panel tool with normal actions.

David Glick
(mobile)

**Comment by jensens** [comment]
gone with PR merge
