### ISSUE TITLE
Docs: remove references to zopeskel; replace with mr.bob.

### ISSUE THREAD

**Issue by smcmahon** [plone/plone.app.dexterity#220]

**Comment by smcmahon** [comment]
I've been thinking about this, and I propose we remove the tutorial sections of the plone.app.dexterity/docs documentation and instead point to the better-maintained resources in docs.plone.org and training.plone.org.

This set of docs would be limited to reference sections and detail explanations.

**Comment by altophen** [comment]
How can I help with this?

**Comment by davilima6** [comment]
Same would be nice for https://github.com/plone/diazo/tree/master/docs

**Comment by gforcada** [comment]
@altophen follow @smcmahon advice: remove docs here and instead point them to docs.plone.org and/or training.plone.org

**Comment by smcmahon** [comment]
This is pretty much done in pull request #222 . Merge welcome.
