### ISSUE TITLE
Is transaction.begin() really needed in the DXFileFactory?

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.app.dexterity#243]
When using the `DXFileFactory` we are calling `transaction.begin()`:

-
 https://github.com/plone/plone.app.dexterity/blob/5256b37e7b5b4b9a312af4123a9137c29ec5a086/plone/app/dexterity/factories.py#L41

I do not think we need it at all.

In addition it looks like the invocation of transaction begin is wiping out all changes done before it, see this test:
```
ipdb> self.context
<PloneSite at /Plone>
ipdb> self.context.test_begin = 1
ipdb> self.context.test_begin
1
ipdb> import transaction
ipdb> transaction.begin()
<transaction._transaction.Transaction object at 0x7fdce4631c90>
ipdb> self.context.test_begin
*** AttributeError: test_begin
```

**Comment by ale-rt** [comment]
I added the "question" label because I would like to have some suggestion from more expert devs.
If anyone can give its opinion it will be great, otherwise I will just submit a PR that will remove the `transaction.begin` innvocation.

**Comment by jensens** [comment]
I would say it is because of the reindexing. But with latest changes of plone/Products.CMFPlone#1343 this is -afaik - superfluous anyway. Even before it's indeed questionable if it is the right way to deal with the problem.

**Comment by ale-rt** [comment]
Thanks @jensens 
I am going to submit a PR to remove that line.
