### ISSUE TITLE
Prerequisites' Documentation

### ISSUE THREAD

**Issue by escodebar** [plone/plone.app.dexterity#252]
Hi everyone!

There seems to be a small typography error in the prerequisites' documentation.
This typo breaks the RST code, making a part of the documentation incomprehensible.

Here two shots of how I see the error:
![screen shot 2017-07-09 at 13 38 34](https://user-images.githubusercontent.com/26252388/27993585-93930b96-64ad-11e7-9ead-68a1b28125b0.png)
![screen shot 2017-07-09 at 13 38 39](https://user-images.githubusercontent.com/26252388/27993586-939c1ad8-64ad-11e7-9d33-359ddc5b0a15.png)

This is how it probably should look like:
![screen shot 2017-07-09 at 13 48 25](https://user-images.githubusercontent.com/26252388/27993602-cb3bc47a-64ad-11e7-856d-26cb9d1a5208.png)
![screen shot 2017-07-09 at 13 48 29](https://user-images.githubusercontent.com/26252388/27993645-22bd2c2a-64ae-11e7-9118-637e304b079f.png)

This is what I believe to cause all the trouble:
![screen shot 2017-07-09 at 13 38 45](https://user-images.githubusercontent.com/26252388/27993669-7e7c2e6c-64ae-11e7-9342-8d203a6d3f2a.png)

And this is when it happened:
https://github.com/plone/plone.app.dexterity/commit/4a59c73b96037eaf625db4a71e4a8e21f456b36e#diff-d7fd6f886530fea3db7c3a4ff0216ce7R126

Cheers!

**Comment by jensens** [comment]
Thanks!
