### ISSUE TITLE
Need a way to remove local IFactory utility when a global version is installed

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#26]
_Original author: wichert@gmail.com (September 15, 2009 20:38:57)_

I am trying to setup a custom factory for a content type I have. Defining a
custom factory and registering turns out to be simple:

from plone.dexterity.factory import DexterityFactory
class Factory(DexterityFactory):
    &quot;&quot;&quot;Factory utility for :obj:`SurveyGroup` instances. This replaces the
default
    :obj:`plone.dexterity.factory.DexterityFactory` factory. When creating a
    new `Surveygroup` instance it also creates an initial
    :obj:`euphorie.content.survey.Survey`.
    &quot;&quot;&quot;
    portal_type = &quot;euphorie.surveygroup&quot;

```
def __init__(self):
    pass

def __call__(self, *args, **kw):
    import pdb ; pdb.set_trace()
    obj=super(Factory, self).__call__(*args, **kw)
    return obj
```

along with this bit of zcml:

```
&lt;utility
    factory=&quot;.surveygroup.Factory&quot;
    provides=&quot;zope.component.interfaces.IFactory&quot;
    name=&quot;euphorie.surveygroup&quot; /&gt;
```

My factory is never called though because earlier during development I did
not have that utility, which caused dexterity to register a new persistent
utility in the local site manager. That utility is preferred over my new
one. That is a little bit unexpected when you hit that for the first time,
but not unacceptable. What is problematic is that there does not seem to be
a way to make that persisted local utility go away. Perhaps dexterity
should have a big 'reset entire state' switch somewhere which clears all
FTI caches and cleans up utility registrations?

For now the only option I see is to register my factory under a different
name and configure that as factory in the FTI.

Thinking a bit about this perhaps dexterity should be simplified here:
instead of using a persistent default utility why not make the standard add
form a bit smarter? The add form could check for a utility, and if none
exist create a DexterityFactory instance itself. That removes the need for
persistent utilities and would make creating custom factories more
transparant as well.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=81_

**Comment by jensens** [comment]
outdated
