### ISSUE TITLE
disabling global_allow makes contenttype unusable (no local allow too)

### ISSUE THREAD

**Issue by iham** [plone/plone.app.dexterity#262]
i wanted to have a contenttype which is only allowed in ONE folder.

according to that i disabled the global allowance to be added anywhere and wanted to add it only in a particular folder using the localhost:8080/Plone/afolder/**folder_constraintypes_form**

sadly the type i want to use doesn't show up.
also i cant add it using plone.api.content.create() -> "type not allowed"

as a workaround, i made the contenttype available in folders (folder.xml - allowed_content_types). now the type is addable in any folder, what is - again - **not** what i want to achieve.

i can remember plone3 (and maybe plone4) did allow to add none-global types in a folder as mentioned above.

my feeling is, that somewhere [here](https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/behaviors/constrains.py#L76) is a problem, how it is determined when/where/which types are allowed to be added.

can someone help?

i don't want to do any hacks, like changing permission for this type, or hiding it in another way. even with global_allow disabled a contenttype needs to be selectable on the folder_constraintypes_form...

**Comment by davisagli** [comment]
I think you're mistaken that we used to support selecting non-globally-allowed types in the constraints form, but I could be wrong. It does sound useful, although I wonder then how we should designate types that should *only* be allowed inside a particular other type and still not available for selection on the constraints form (I don't want to see all the PloneFormGen field types there, for example).

When I've needed to do what you're aiming for, I've achieved it by enabling global_allow, giving the type an add permission that is disabled at the site root, and adding that permission to the Contributor role just on the folder where I want the type to be addable. I consider this taking advantage of Plone's permission system rather than a hack, but it's a bit non-ideal since Managers can still add the type elsewhere.

**Comment by iham** [comment]
may it be plone2.5? nevermind. i am pretty sure, there was a time, when this (allowing a globally disabled contenttype in certain folderish objects) was possible via the UI. 

the permission-idea is - as you say - non-ideal.

i considered selecting a type locally to be straight forward. sadly it is not.

the pfg-fields are coupled to a pfg-form (folder); so no pollution of the add menu and where to put a form is not wise to restrict. otherwise ... why not. create a "contact" folder, allow pfg stuff only there, done.

adding a separate folder type wouldnt' solve my problem, as i don't want to see that folder everywhere again - same as the type i want to only be allowed to add to a single (or certain) folder(s).

but back to topic:
i think, disabling global_allow should NOT automatically forbid to add a type locally. currently it is implemented as if a global "no" means local "no". thats sort of missleading in my opinion.

**Comment by iham** [comment]
basic problem:
global type vs local type
- a global type is addable anywhere
- a local type is not addable anywhere and MUST be defined in allowed_content_types in order to be addable in its container
- there was no chance to add a locally addable type which is not defined in allowed_content_types of a container type. even not to add them on an object using the folder_constraintypes_form (add -> restriction)
- a locally addable type is not able to be added using plone.api.content, even if "telling" a container-obj, it is allowed to.

... but i did it!

"available types" are:
- global allowed types (like File, Folder, Plone Form Gen Folder, ...)
- subtypes if their container is the defined one (think of pfg email field)
- types which are not global allowed, but addable to be locally allowed inside a container object)

types, which are not global
- i needed to:
  - override "plone.app.content.ValidAddableTypes" Vocabulary, which displays the checkboxes of the available types in the folder_constraintypes_form, to make them select- and store-able.

  - fix the following methods as they never checked correctly for locally_allowed_types
    - override the "plone.constraintypes" behaviors methods:
      - allowedContentTypes()
      - getLocallyAllowedTypes()
      - setLocallyAllowedTypes()
    - override the Dexterity "Folder" methods: (maybe ill need to consider "Collection" too...)
      - invokeFactory()
      - _verifyObjectPaste()

the following packages are involved
- **Products.CMFCore** (PortalFolderBase.invokeFactory)
- **plone.dexterity** (PasteBehaviourMixin._verifyObjectPaste)
- **plone.app.dexterity** (ConstrainTypesBehavior)
- **plone.app.content** (constraintypes.ValidTypes)

TODO:
implement those and think about how to deal with Collections ...
(maybe it will be easy, as the invokeFactory and _verifyObjectPaste are not subclassed and therefore implemented in there base classes. ... maybe)

@jensens, @davisagli, @agitator, @agitator, @gogobd:
i am thinking about implementing this during the alpine city sprint in the end of January.
i have to allowance to do so from my boss to contribute my work on this topic.

**Comment by iham** [comment]
all is bad ;)

several ideas about how to make types addable came up...
the best solution seams to be:
create a folder inside the plone instance and deselect types you don't want to be added anywhere and reintroduce these types on a deeper lying folder.

the type **must** be globally allowed anyway.

the global_allow IS restricted to be used exclusively with allowed_content_types and since nobody wants to touch cmfcore, this will stay the way it is ;)
