### ISSUE TITLE
Upload lock is not released when name chooser fails

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.dexterity#276]
When uploading a file or image, a lock is acquired, and afterwards released, something like this:

```
upload_lock.acquire()
newid = chooser.chooseName(name, self.context.aq_parent)
try:
    # do stuff:
finally:
    upload_lock.release()
```

I am working on a part of the name chooser, and apparently I currently have an error that makes it throw a `ValueError:  Cannot find a unique name based on test after 100 attemps.`
Problem is that this ValueError is raised outside of the `try/finally`, so the upload lock is never released. A new upload will hang indefinitely, waiting for a change to acquire the lock.

I found this while running the tests, but in corner cases it could happen on a real site. To reproduce:

- Edit `factories.py` to raise a ValueError instead of calling `chooser.chooseName`.
- Run `bin/test -s plone.app.content -m test_widgets -t testFileUpload` in coredev 5.2.

This will run two tests (`testFileUpload` and `testFileUploadTxt`). The first test gives a `ValueError`. The second test never quits, because it keeps waiting to acquire the lock.
The order of tests does not matter.
If you run only one test, it will error and exit just fine.

Solution is of course to move the name choosing within the `try/finally` block.
I will do so.

**Comment by davisagli** [comment]
Nice find!

**Comment by mauritsvanrees** [comment]
Oops, I accidentally pushed a fix directly to master... Sorry. If this breaks Jenkins (5.1 and 5.2) anyone should feel free to immediately revert.
Seems safe though.
I made a PR for Plone 5.0: https://github.com/plone/plone.app.dexterity/pull/277
