### ISSUE TITLE
Make behaviors UI clearer to avoid selecting duplicates

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#29]
_Original author: wich...@wiggy.net (March 02, 2010 10:28:18)_

<b>What steps will reproduce the problem?</b>
1. Create a new type via the plone control panel
2. Enable the 'Basic metadata' behaviour
3. Add an instance of this type to the site

The add form now has two title and two description fields.

The configuration I used is:

extends =
    http://dist.plone.org/release/4.0a5/versions.cfg
    http://dist.plone.org/release/4.0a5/sources.cfg
    http://good-py.appspot.com/release/dexterity/2.0-next

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=108_

**Comment by jensens** [comment]
outdated
