### ISSUE TITLE
Update tests to match plone.dexterity changes

### ISSUE THREAD

**Issue by avoinea** [plone/plone.app.dexterity#313]
See https://github.com/plone/plone.dexterity/pull/137

**Comment by mauritsvanrees** [comment]
I still see this go wrong sometimes, especially with pull requests on Plone 5.2 on Python 2.

- https://jenkins.plone.org/job/pull-request-5.2/1673/testReport/plone.app.dexterity/tests/editing_rst/
- https://jenkins.plone.org/job/pull-request-5.2/1668/testReport/junit/plone.app.dexterity/tests/editing_rst/
- https://jenkins.plone.org/job/pull-request-5.2/1665/

I wonder if you can do anything about that.

**Comment by mauritsvanrees** [comment]
I wonder if it helps to sleep one second between each of these tests.

**Comment by avoinea** [comment]
> I wonder if it helps to sleep one second between each of these tests.

`0.1`, `0.2` would be enough to do the trick.

**Comment by avoinea** [comment]
> `0.1`, `0.2` would be enough to do the trick.

Hmm, or maybe not. Timestamp in the above example is  `1602233786_2_0` -> `1602233786.0`, thus no milliseconds.
