### ISSUE TITLE
TTW changes to filesystem-defined schema lost after restart

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#33]
_Original author: ems...@psu.edu (September 13, 2010 15:47:22)_

<b>What steps will reproduce the problem?</b>

With a filesystem-defined schema, edit the type through the Dexterity types control panel. The fields will display on edit forms, but after restarting Zope, they've disappeared.

Stepping into plone.app.dexterity.serialize.serializeSchema, a ValueError is raised when 'IMyContentType' (schema.**name**) is passed to splitSchemaName. That error gets swallowed as &quot;not a dexterity schema&quot;. 

<b>What version of the product are you using? On what operating system?</b>
1.0b2, Plone 4.0

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=139_

**Comment by jensens** [comment]
works for me

**Comment by mck9** [comment]
I still have this issue on Plone 5.2 (6 years later)
