### ISSUE TITLE
Rename "Dexterity Content Types" to just "Content Types"

### ISSUE THREAD

**Issue by tisto** [plone/plone.app.dexterity#331]
PR: https://github.com/plone/plone.app.dexterity/pull/341

**Comment by stevepiercy** [comment]
It looks like this was closed by https://github.com/plone/plone.app.dexterity/pull/341.

**Comment by ale-rt** [comment]
Yes
![image](https://user-images.githubusercontent.com/1300763/189096778-b485ce50-26b2-40ee-8dae-2e3c46b76b86.png)
