### ISSUE TITLE
@@folder_contents always lists size of dexterity item as "0 kB"

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#34]
_Original author: kleist.i...@gmail.com (November 01, 2010 09:32:07)_

This is using &quot;http://good-py.appspot.com/release/dexterity/1.0b2?plone=4.0.1&quot;

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=146_

**Comment by jensens** [comment]
Checked with large file and images: shown with size
