### ISSUE TITLE
plone.app.dexterity related behaviors naive

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#35]
_Original author: runy...@gmail.com (January 07, 2011 18:42:13)_

http://dev.plone.org/plone/ticket/11395  

the z3c.relationfield does not know about aq_wrappers.
this emans plone.app.dexterity relateditems behavior should 
ensure aq wrapping is done.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=150_

**Comment by jensens** [comment]
outdated
