### ISSUE TITLE
Support "Exclude from navigation" and "Allow comments" content item settings

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#36]
_Original author: laurence...@gmail.com (February 01, 2011 17:15:58)_

Dexterity is currently missing behaviours to support the &quot;Exclude from navigation&quot; and &quot;Allow comments&quot; content item settings, supported by ATContentTypes and appearing on the 'Settings' fieldset.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=155_

**Comment by jensens** [comment]
no issue any longer
