### ISSUE TITLE
Content from a content type created TTW are not searchable

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#37]
_Original author: euidz...@gmail.com (February 23, 2011 15:56:26)_

<b>What steps will reproduce the problem?</b>
1.Create a custom type TTW with dexterity with a text field
2.Create a content (says object1) from this type, fill the text with &quot;textA&quot;
3.Search for &quot;textA&quot; using the search tools in the plone site

<b>What is the expected output? What do you see instead?</b>
The search should return the object1 entry. Instead it gives no result.

<b>What version of the product are you using? On what operating system?</b>
Dexterity Content Types - Plone Integration 1.0b3

in my buildout : 
extends = 

http://good-py.appspot.com/release/dexterity/1.0b7?plone=4.0.3

[versions]
# avoid a bug in the TWW interface when configuring a RichText field

Products.TinyMCE = 1.1.7
# avoid bug 133

plone.supermodel = 1.0b6

<b>Please provide any additional information below.</b>

Looking at the object1 entry in the zcatalog through the ZMI show that the SearchableText tuple is empty.

This is confusing because the TTW interface is rendered useless if the contents are not searchable.

I suggest that the new field form in the TTW interface allows to specify if the field is searchable or not, leading to the correct registration of the new objects in the zcatalog.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=157_

**Comment by jensens** [comment]
outdated
