### ISSUE TITLE
Categories edit form does not propose existing tags

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#38]
_Original author: euidz...@gmail.com (February 25, 2011 16:31:36)_

<b>What steps will reproduce the problem?</b>
1.create a dexterity type
2.activate the behavior &quot;Categorization&quot;
3.create one objet of this type, go to the categorization tab 

<b>What is the expected output? What do you see instead?</b>

One expect the usual Categorie form displaying all existing tags in a box to allow picking one or more tags.

Instead there is only an empty input box for categories

<b>What version of the product are you using? On what operating system?</b>
1.0b3 on plone 4.0.3 (on debian squeeze).

<b>Please provide any additional information below.</b>
Note that the tags added to the dexterity object are correctly available to the non dexterity object in the site.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=158_

**Comment by jensens** [comment]
no issue any longer
