### ISSUE TITLE
Error when view folder with folder_full_view view

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#40]
_Original author: heat...@gmail.com (May 07, 2011 15:53:37)_

<b>What steps will reproduce the problem?</b>
1. Create dexterity content-type (telefones)
2. Add telefone content in folder
3. view using folder-full-view

<b>What is the expected output? What do you see instead?</b>
All content and field content.

what i'm see:

Traceback (innermost last):
  Module ZPublisher.Publish, line 126, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module Shared.DC.Scripts.Bindings, line 322, in **call**
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 240, in _exec
  Module Products.CMFCore.FSPageTemplate, line 180, in pt_render
  Module Products.PageTemplates.PageTemplate, line 79, in pt_render
  Module zope.pagetemplate.pagetemplate, line 113, in pt_render
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module Products.PageTemplates.Expressions, line 218, in evaluateStructure
  Module zope.tales.tales, line 696, in evaluate
- URL: file:/home/plone/.buildout/eggs/Products.CMFPlone-4.1b2-py2.6.egg/Products/CMFPlone/skins/plone_content/folder_full_view.pt
- Line 17, Column 24
- Expression: &lt;PythonExpr item.getObject().folder_full_view_item()&gt;
- Names:
    {'container': &lt;PloneSite at /plonesite&gt;,
     'context': &lt;ATFolder at /plonesite/secretarias&gt;,
     'default': &lt;object object at 0x7f9a194574c0&gt;,
     'here': &lt;ATFolder at /plonesite/secretarias&gt;,
     'loop': {u'item': &lt;Products.PageTemplates.Expressions.PathIterator object at 0xecf73d0&gt;},
     'nothing': None,
     'options': {'args': ()},
     'repeat': &lt;Products.PageTemplates.Expressions.SafeMapping object at 0xecde050&gt;,
     'request': &lt;HTTPRequest, URL=http://187.33.1.14:8080/plonesite/secretarias/folder_full_view&gt;,
     'root': &lt;Application at &gt;,
     'template': &lt;FSPageTemplate at /plonesite/folder_full_view used for /plonesite/secretarias&gt;,
     'traverse_subpath': [],
     'user': &lt;PropertiedUser 'admin'&gt;}
  Module Products.PageTemplates.ZRPythonExpr, line 48, in **call**
- **traceback_info**: item.getObject().folder_full_view_item()
  Module PythonExpr, line 1, in &lt;expression&gt;
  Module Shared.DC.Scripts.Bindings, line 322, in **call**
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 240, in _exec
  Module Products.CMFCore.FSPageTemplate, line 180, in pt_render
  Module Products.PageTemplates.PageTemplate, line 79, in pt_render
  Module zope.pagetemplate.pagetemplate, line 113, in pt_render
- Warning: Macro expansion failed
- Warning: &lt;type 'exceptions.KeyError'&gt;: 'item_macro'
  Module zope.tal.talinterpreter, line 271, in **call**
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 819, in do_loop_tal
  Module zope.tales.tales, line 682, in setRepeat
  Module zope.tales.tales, line 696, in evaluate
- URL: /home/plone/.buildout/eggs/plone.app.dexterity-1.0rc1-py2.6.egg/plone/app/dexterity/browser/item.pt
- Line 13, Column 4
- Expression: &lt;PathExpr standard:u'view/widgets/values'&gt;
- Names:
    {'container': &lt;PloneSite at /plonesite&gt;,
     'context': &lt;Item at /plonesite/secretarias/secretaria-de-comunicacao&gt;,
     'default': &lt;object object at 0x7f9a194574c0&gt;,
     'here': &lt;Item at /plonesite/secretarias/secretaria-de-comunicacao&gt;,
     'loop': {},
     'nothing': None,
     'options': {'args': ()},
     'repeat': &lt;Products.PageTemplates.Expressions.SafeMapping object at 0xe32f100&gt;,
     'request': &lt;HTTPRequest, URL=http://187.33.1.14:8080/plonesite/secretarias/folder_full_view&gt;,
     'root': &lt;Application at &gt;,
     'template': &lt;FSPageTemplate at /plonesite/folder_full_view_item used for /plonesite/secretarias/secretaria-de-comunicacao&gt;,
     'traverse_subpath': [],
     'user': &lt;PropertiedUser 'admin'&gt;}
  Module zope.tales.expressions, line 217, in **call**
  Module Products.PageTemplates.Expressions, line 147, in _eval
  Module zope.tales.expressions, line 124, in _eval
  Module Products.PageTemplates.Expressions, line 97, in trustedBoboAwareZopeTraverse
  Module zope.traversing.adapters, line 136, in traversePathElement
- **traceback_info**: (&lt;Products.Five.metaclass.Plone object at 0xecf7810&gt;, 'widgets')
  Module zope.traversing.adapters, line 50, in traverse
- **traceback_info**: (&lt;Products.Five.metaclass.Plone object at 0xecf7810&gt;, 'widgets', ['values'])
  LocationError: (&lt;Products.Five.metaclass.Plone object at 0xecf7810&gt;, 'widgets')

<b>What version of the product are you using? On what operating system?</b>
Plone 4.1

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=172_

**Comment by jensens** [comment]
outdated
