### ISSUE TITLE
form.model() can't be used with value adapters

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#41]
_Original author: steve@dcn.org (May 08, 2011 23:24:30)_

Code like:

class IExampleTrial(form.Schema):
    form.model(&quot;models/example_trial.xml&quot;)

@form.default_value(field=IExampleTrial['text_line'])
def default_title(data):
    return 'try me!'

Will cause a key error for 'text_line' (which is in the model). However,

class IExampleTrial(form.Schema):
    form.model(&quot;models/example_trial.xml&quot;)
    text_line = schema.TextLine(title=u'Text Line')

@form.default_value(field=IExampleTrial['text_line'])
def default_title(data):
    return 'try me!'

Succeeds. I assume the problem with the former is because martian processing of the form.model directive has not yet completed.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=173_

**Comment by jensens** [comment]
outdated
