### ISSUE TITLE
Editing of short names doesn't seem to work

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#42]
_Original author: anthonyg...@gmail.com (May 12, 2011 11:36:18)_

<b>What steps will reproduce the problem?</b>
1. Login as admin
2. site setup / editing - check &quot;Show 'Short Name' on content?&quot; and click save
3. preferences / Personal Preferences - check &quot;Allow editing of Short Names&quot; and click save
4. go to root of site, click add and select a dexterity content type

<b>What is the expected output? What do you see instead?</b>

Expected: short name field displayed allowing you to set the short name of the content item

Actual: don't see short name field.  Also don't see it when editing items

<b>What version of the product are you using? On what operating system?</b>
Plone 4.1b2, Dexterity 1.0rc1.  Windows and Linux

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=174_

**Comment by agitator** [comment]
what's the state of this issue?

**Comment by agitator** [comment]
this is solved as behavior plone.app.dexterity.behaviors.id.IShortName
