### ISSUE TITLE
Dexterity types implementing the referenceable behavior do not test as referenceable by AT ReferenceEngine

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#43]
_Original author: c...@crisewing.com (May 12, 2011 22:49:02)_

Products.Archetypes.ReferenceEngine.ReferenceCatalog has an 'isReferenceable' method, which is implemented like so:

```
def isReferenceable(self, object):
    return (IReferenceable.providedBy(object) or
            shasattr(object, 'isReferenceable'))
```

a dexterity content type which has the referenceable behavior from plone.app.referenceablebehavior implements an interface called IReferenceable, but this interface, which is defined in plone.app.referenceablebehavior.reference is _not_ in any way related to the IReferenceable interface above, which comes from Products.Archetypes.interfaces.referenceable

This means that when you try to look up a reference to such a dexterity type using the reference catalog, you end up with a ReferenceException like this:

```
ReferenceException: &lt;Item at m1&gt; not referenceable
```

The problem in this case arises because we've got an archetypes type with a reference field that points to a dexterity type and we'd like to implement a method to look up all items of that type with references to the dexterity object from the context of the dexterity object.  The simplest and cleanest way to do this would be to call reference_catalog.getBackReferences(item, relationship=&quot;foo&quot;), but because of this problem, that method is not available.  I'm going to have to implement a new catalog index on the relationship field so I can do a catalog lookup for this view.

Any thoughts on how this could be fixed?

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=176_

**Comment by jensens** [comment]
outdated
