### ISSUE TITLE
Improve z3c.form text & textline widgets when max_length is specified

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#46]
_Original author: dgl...@gmail.com (July 20, 2011 04:12:07)_

Feedback from Liz:

&quot;Max length validation is wrong. It just cuts things off. As an end user, I type something and then on save its gone. There is no counter or warning or anything. In most cases I assume the end user won't be the person who created the type and won't have this inside knowledge.&quot;

We could possibly steal the counter from PloneFormGen's text fields, or use HTML5 validation to give the user feedback sooner.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=208_

**Comment by jensens** [comment]
outdated and not dx
