### ISSUE TITLE
Contraint not satisfied error

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#50]
_Original author: camemb...@gmail.com (September 07, 2011 17:27:25)_

<b>What steps will reproduce the problem?</b>
1. add a field, make it required, multi select add a couple options
2. make the default None
3. KABOOM

<b>What is the expected output? What do you see instead?</b>
There are lots of use cases where you want someone to physically click something (anything legal really). You want nothing to be selected by default but then force an error if they don't chose something.

<b>What version of the product are you using? On what operating system?</b>
http://good-py.appspot.com/release/dexterity/2.0-next?plone=4.1

<b>Please provide any additional information below.</b>
Module ZPublisher.Publish, line 126, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 46, in call_object
Module plone.z3cform.layout, line 70, in **call**
Module plone.z3cform.layout, line 54, in update
Module z3c.form.form, line 210, in update
Module z3c.form.action, line 99, in execute
Module z3c.form.button, line 311, in **call**
Module z3c.form.button, line 170, in **call**
Module plone.schemaeditor.browser.field.edit, line 66, in handleSave
Module z3c.form.button, line 170, in **call**
Module z3c.form.form, line 294, in handleApply
Module z3c.form.form, line 275, in applyChanges
Module z3c.form.form, line 52, in applyChanges
Module z3c.form.datamanager, line 76, in set
Module plone.schemaeditor.fields, line 92, in **setattr**
Module zope.schema._bootstrapfields, line 44, in __set__
Module zope.schema._bootstrapfields, line 153, in validate
Module zope.schema._field, line 326, in _validate
ConstraintNotSatisfied: None

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=227_

**Comment by jensens** [comment]
outdated
