### ISSUE TITLE
RichText field w. non html mime type: Add/Edit form partly TinyMCE enabled if content empty

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#53]
_Original author: kleist.i...@gmail.com (November 14, 2011 04:33:57)_

Plone 4.2 coredev buildout, plone.app.textfield trunk

(moved from Trac, see also a related ticket http://dev.plone.org/ticket/11228)

The schema of a Dexterity type has a RichText field using the mime type &quot;application/xml&quot;: 

```
form.primary('doc_entity')
doc_entity = RichText(
        required=False,
        title=_(u'Document entity'),
        description=_(u'The root of the XML document'),
        default_mime_type='application/xml',
        allowed_mime_types=('application/xml',),
        output_mime_type='text/html'
)
```

This works surprisingly well, the add and edit forms render a plain &quot;textarea&quot; with almost no trace of TinyMCE. But just almost:
- Under the textarea is a link &quot;Edit without visual editor&quot;
- The textarea is of class &quot;mce_editable&quot;, and has a &quot;title&quot; attribute containing this:

&quot;{&amp;quot;valid_elements&amp;quot;: {&amp;quot;code&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;kbd&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;aside&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;img&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;alt&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;height&amp;quot;, &amp;quot;hspace&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;ismap&amp;lt;ismap&amp;quot;, &amp;quot;longdesc&amp;quot;, &amp;quot;name&amp;quot;, &amp;quot;src&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;, &amp;quot;usemap&amp;quot;, &amp;quot;vspace&amp;quot;, &amp;quot;width&amp;quot;], &amp;quot;title&amp;quot;: [&amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;], &amp;quot;tt&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;tr&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;char&amp;quot;, &amp;quot;charoff&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;li&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;, &amp;quot;type&amp;quot;], &amp;quot;source&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;tfoot&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;char&amp;quot;, &amp;quot;charoff&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;th&amp;quot;: [&amp;quot;abbr&amp;quot;, &amp;quot;align&amp;quot;, &amp;quot;axis&amp;quot;, &amp;quot;char&amp;quot;, &amp;quot;charoff&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;colspan&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;headers&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;nowrap&amp;quot;, &amp;quot;rowspan&amp;quot;, &amp;quot;scope&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;td&amp;quot;: [&amp;quot;abbr&amp;quot;, &amp;quot;align&amp;quot;, &amp;quot;axis&amp;quot;, &amp;quot;char&amp;quot;, &amp;quot;charoff&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;colspan&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;headers&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;nowrap&amp;quot;, &amp;quot;rowspan&amp;quot;, &amp;quot;scope&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;dl&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;compact&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;blockquote&amp;quot;: [&amp;quot;cite&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;big&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;dd&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;meter&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;dt&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;p&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;small&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;output&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;div&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;em&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;datalist&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;hgroup&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;meta&amp;quot;: [&amp;quot;content&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;http-equiv&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;name&amp;quot;, &amp;quot;scheme&amp;quot;], &amp;quot;video&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;rt&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;canvas&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;rp&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;sub&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;bdo&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;sup&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;progress&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;body&amp;quot;: [&amp;quot;alink&amp;quot;, &amp;quot;background&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;link&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;text&amp;quot;, &amp;quot;title&amp;quot;, &amp;quot;vlink&amp;quot;], &amp;quot;acronym&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;base&amp;quot;: [&amp;quot;href&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;target&amp;quot;], &amp;quot;br&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;clear&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;address&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;article&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;strong&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;ol&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;compact&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;, &amp;quot;type&amp;quot;], &amp;quot;caption&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;dialog&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;col&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;char&amp;quot;, &amp;quot;charoff&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;span&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;, &amp;quot;width&amp;quot;], &amp;quot;h2&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;h3&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;h1&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;h6&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;h4&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;h5&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;header&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;table&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;summary&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;span&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;area&amp;quot;: [&amp;quot;accesskey&amp;quot;, &amp;quot;alt&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;coords&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;href&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;nohref&amp;quot;, &amp;quot;shape&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;tabindex&amp;quot;, &amp;quot;target&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;mark&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;dfn&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;var&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;cite&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;thead&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;char&amp;quot;, &amp;quot;charoff&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;head&amp;quot;: [&amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;profile&amp;quot;], &amp;quot;hr&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;noshade&amp;quot;, &amp;quot;size&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;, &amp;quot;width&amp;quot;], &amp;quot;ruby&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;b&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;colgroup&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;char&amp;quot;, &amp;quot;charoff&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;span&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;, &amp;quot;width&amp;quot;], &amp;quot;keygen&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;ul&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;compact&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;, &amp;quot;type&amp;quot;], &amp;quot;del&amp;quot;: [&amp;quot;cite&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;datetime&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;pre&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;, &amp;quot;width&amp;quot;], &amp;quot;figure&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;ins&amp;quot;: [&amp;quot;cite&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;datetime&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;tbody&amp;quot;: [&amp;quot;align&amp;quot;, &amp;quot;char&amp;quot;, &amp;quot;charoff&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;html&amp;quot;: [&amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;xmlns&amp;quot;], &amp;quot;nav&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;details&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;u&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;samp&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;map&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;name&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;a&amp;quot;: [&amp;quot;accesskey&amp;quot;, &amp;quot;charset&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;coords&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;href&amp;quot;, &amp;quot;hreflang&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;name&amp;quot;, &amp;quot;rel&amp;quot;, &amp;quot;rev&amp;quot;, &amp;quot;shape&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;tabindex&amp;quot;, &amp;quot;target&amp;quot;, &amp;quot;title&amp;quot;, &amp;quot;type&amp;quot;], &amp;quot;footer&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;i&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;q&amp;quot;: [&amp;quot;cite&amp;quot;, &amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;command&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;time&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;audio&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;section&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;], &amp;quot;abbr&amp;quot;: [&amp;quot;class&amp;quot;, &amp;quot;dir&amp;quot;, &amp;quot;id&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;title&amp;quot;]}, &amp;quot;rooted&amp;quot;: false, &amp;quot;labels&amp;quot;: {&amp;quot;label_plain_cell&amp;quot;: &amp;quot;Plain cell&amp;quot;, &amp;quot;label_lists&amp;quot;: &amp;quot;Lists&amp;quot;, &amp;quot;label_no_anchors&amp;quot;: &amp;quot;No anchors in this page&amp;quot;, &amp;quot;label_styles&amp;quot;: &amp;quot;(remove style)&amp;quot;, &amp;quot;label_selection&amp;quot;: &amp;quot;Selection&amp;quot;, &amp;quot;label_print&amp;quot;: &amp;quot;Print&amp;quot;, &amp;quot;label_style_ldots&amp;quot;: &amp;quot;Style...&amp;quot;, &amp;quot;label_text&amp;quot;: &amp;quot;Text&amp;quot;, &amp;quot;label_tables&amp;quot;: &amp;quot;Tables&amp;quot;, &amp;quot;label_no_items&amp;quot;: &amp;quot;No items in this folder&amp;quot;, &amp;quot;label_paragraph&amp;quot;: &amp;quot;Normal paragraph&amp;quot;}, &amp;quot;libraries_spellchecker_choice&amp;quot;: &amp;quot;browser&amp;quot;, &amp;quot;link_using_uids&amp;quot;: false, &amp;quot;content_css&amp;quot;: &amp;quot;Plone/portal_tinymce/@@tinymce-getstyle&amp;quot;, &amp;quot;customplugins&amp;quot;: [&amp;quot;ploneimage&amp;quot;, &amp;quot;plonelink&amp;quot;], &amp;quot;parent&amp;quot;: &amp;quot;http://localhost:8080/Plone/arbortext/&amp;quot;, &amp;quot;resize_horizontal&amp;quot;: false, &amp;quot;toolbar_width&amp;quot;: 440, &amp;quot;editor_width&amp;quot;: 600, &amp;quot;atd_show_types&amp;quot;: &amp;quot;Bias Language,Cliches,Complex Expression,Diacritical Marks,Double Negatives,Hidden Verbs,Jargon Language,Passive voice,Phrases to Avoid,Redundant Expression&amp;quot;, &amp;quot;portal_url&amp;quot;: &amp;quot;Plone&amp;quot;, &amp;quot;atd_ignore_strings&amp;quot;: &amp;quot;Zope,Plone,TinyMCE&amp;quot;, &amp;quot;buttons&amp;quot;: [&amp;quot;save&amp;quot;, &amp;quot;style&amp;quot;, &amp;quot;bold&amp;quot;, &amp;quot;italic&amp;quot;, &amp;quot;justifyleft&amp;quot;, &amp;quot;justifycenter&amp;quot;, &amp;quot;justifyright&amp;quot;, &amp;quot;justifyfull&amp;quot;, &amp;quot;bullist&amp;quot;, &amp;quot;numlist&amp;quot;, &amp;quot;definitionlist&amp;quot;, &amp;quot;outdent&amp;quot;, &amp;quot;indent&amp;quot;, &amp;quot;image&amp;quot;, &amp;quot;link&amp;quot;, &amp;quot;unlink&amp;quot;, &amp;quot;anchor&amp;quot;, &amp;quot;tablecontrols&amp;quot;, &amp;quot;code&amp;quot;, &amp;quot;fullscreen&amp;quot;, &amp;quot;&amp;quot;], &amp;quot;resizing_use_cookie&amp;quot;: true, &amp;quot;livesearch&amp;quot;: true, &amp;quot;document_url&amp;quot;: &amp;quot;http://localhost:8080/Plone/arbortext&amp;quot;, &amp;quot;path_location&amp;quot;: &amp;quot;bottom&amp;quot;, &amp;quot;allow_captioned_images&amp;quot;: false, &amp;quot;table_styles&amp;quot;: [&amp;quot;Invisible grid=invisible&amp;quot;, &amp;quot;Fancy listing=listing&amp;quot;, &amp;quot;Fancy grid listing=grid listing&amp;quot;, &amp;quot;Fancy vertical listing=vertical listing&amp;quot;], &amp;quot;styles&amp;quot;: [&amp;quot;Invisible grid|table|invisible&amp;quot;, &amp;quot;Fancy listing|table|listing&amp;quot;, &amp;quot;Fancy grid listing|table|grid listing&amp;quot;, &amp;quot;Fancy vertical listing|table|vertical listing&amp;quot;, &amp;quot;Heading|h2&amp;quot;, &amp;quot;Subheading|h3&amp;quot;, &amp;quot;Literal|pre&amp;quot;, &amp;quot;Discreet|span|discreet&amp;quot;, &amp;quot;Pull-quote|blockquote|pullquote&amp;quot;, &amp;quot;Call-out|p|callout&amp;quot;, &amp;quot;Highlight|span|visualHighlight&amp;quot;, &amp;quot;Disc|ul|listTypeDisc&amp;quot;, &amp;quot;Square|ul|listTypeSquare&amp;quot;, &amp;quot;Circle|ul|listTypeCircle&amp;quot;, &amp;quot;Numbers|ol|listTypeDecimal&amp;quot;, &amp;quot;Lower Alpha|ol|listTypeLowerAlpha&amp;quot;, &amp;quot;Upper Alpha|ol|listTypeUpperAlpha&amp;quot;, &amp;quot;Lower Roman|ol|listTypeLowerRoman&amp;quot;, &amp;quot;Upper Roman|ol|listTypeUpperRoman&amp;quot;, &amp;quot;Definition term|dt&amp;quot;, &amp;quot;Definition description|dd&amp;quot;, &amp;quot;Odd row|tr|odd&amp;quot;, &amp;quot;Even row|tr|even&amp;quot;, &amp;quot;Heading cell|th|&amp;quot;, &amp;quot;Page break (print only)|div|pageBreak&amp;quot;, &amp;quot;Clear floats|div|visualClear&amp;quot;], &amp;quot;navigation_root_url&amp;quot;: &amp;quot;http://localhost:8080/Plone&amp;quot;, &amp;quot;editor_height&amp;quot;: 400, &amp;quot;toolbar_location&amp;quot;: &amp;quot;top&amp;quot;, &amp;quot;autoresize&amp;quot;: false, &amp;quot;atd_rpc_url&amp;quot;: &amp;quot;Plone/@@&amp;quot;, &amp;quot;valid_inline_styles&amp;quot;: [&amp;quot;text-align&amp;quot;, &amp;quot;list-style-type&amp;quot;, &amp;quot;float&amp;quot;, &amp;quot;padding-left&amp;quot;], &amp;quot;resizing&amp;quot;: true, &amp;quot;atd_rpc_id&amp;quot;: &amp;quot;Products.TinyMCE-kleist&amp;quot;, &amp;quot;language&amp;quot;: &amp;quot;en&amp;quot;, &amp;quot;contextmenu&amp;quot;: true, &amp;quot;entity_encoding&amp;quot;: &amp;quot;raw&amp;quot;, &amp;quot;directionality&amp;quot;: &amp;quot;ltr&amp;quot;}

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=242_

**Comment by jensens** [comment]
outdated
