### ISSUE TITLE
Loss of type factory utility registration from non-unique names

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#55]
_Original author: j...@lentin.co.uk (November 17, 2011 17:39:35)_

fti.py seems to assume that the factory name is unique, at least in unregister() and ftiModified(), but it's fairly easy to create multiple FTIs with the same factory name without being too devious/inept.

<b>What steps will reproduce the problem?</b>
1. Create &quot;nice_type&quot; type using the TTW editor.
2. In ZMI, portal_types, copy and paste &quot;nice_type&quot;. At this point there is a &quot;copy_of_nice_type&quot; which has the same Title and factory as &quot;nice_type&quot;.
3. Rename type to &quot;very_nice_type&quot;
4. Update Title and factory to match.
5. plone.dexterity.fti.ftiModified() removes the &quot;nice_type&quot; factory utility, and adds a &quot;very_nice_type&quot; utility.
6. You can no longer add &quot;nice_type&quot; objects, since they have no factory utility.

A quick fix would be for ftiModified() should check it's not removing a factory that is already being used, and I might have a bash at that tomorrow.

However, should we have gotten into this state in the first place? Is a non-unique factory field an error? As far as my limited investigation can see, having a separate factory name field is a hindrance rather than a help. The factory field staying empty by default and fti.py using the FTI name as a fallback would have made our lives a lot easier, for example.

This was tested with a Plone 4.2a2 and plone.dexterity master, although originally noticed this on 4.1.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=245_

**Comment by jensens** [comment]
outdated
