### ISSUE TITLE
collective.z3cform.datagridfield gives error in Dexterity custom type

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#56]
_Original author: mjm...@webtothemax.com (November 26, 2011 22:41:40)_

I created a simple type in Dexterity 1.1/Plone4.1.2 similar tot the example in DataGridField docs. 
I have no custom view template, no custom view class. 

The custom content type seems to work, i.e. when creating an instance the subform of the data grid field shows correctly and one can enter the fields one through three. But when the Add button is pressed, a new empty row is displayed (as it should, but there is also an error message of the first row &quot;The system could not process the given value&quot;.

This may or may not be a bug. If not, a concrete example of the use of the DataGridField in the Dexterity manual would be welcome. TIA!
# Source for the content type

from five import grok

from zope import schema
from zope.interface import Invalid, Interface
from zope.component import getMultiAdapter

from Products.CMFCore.utils import getToolByName

from plone.memoize.instance import memoize
from plone.directives import form
from plone.app.textfield import RichText
from plone.namedfile.field import NamedBlobImage
from plone.namedfile.interfaces import IImageScaleTraversable
from plone.formwidget.contenttree import ObjPathSourceBinder

from z3c.form import field, button
from z3c.relationfield.schema import RelationList, RelationChoice
from collective.z3cform.datagridfield import DataGridFieldFactory, DictRow

from wttm.decisions import WttmDecisionsFactory as _

class ITableRowSchema(Interface):
    one = schema.TextLine(title=u&quot;One&quot;)
    two = schema.TextLine(title=u&quot;Two&quot;)
    three = schema.TextLine(title=u&quot;Three&quot;)

class IDecisionNodeFolder(Interface):
    four = schema.TextLine(title=u&quot;Four&quot;)

```
# form.widget(table=DataGridFieldFactory)  # doesn't seem to help
table = schema.List(title=u&quot;My Table&quot;,
                    value_type=DictRow(title=u&quot;tablerow&quot;, schema=ITableRowSchema))
```

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=246_

**Comment by jensens** [comment]
outdated
