### ISSUE TITLE
Relationfield and cmfeditions

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#57]
_Original author: jvlooth...@gmail.com (December 24, 2011 09:58:15)_
- Run buildout with the attached demo
- Create Plone site with the bug demo extension
- Create &quot;Bug A&quot;
- Create &quot;Bug B&quot;, link it to &quot;Bug A&quot;
- Go to site setup
- Go to types
- Enable automatic versioning for Bug
- Edit &quot;Bug B&quot;
- Save

You will now see an error:

Traceback (innermost last):
  Module ZPublisher.Publish, line 126, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module plone.z3cform.layout, line 70, in **call**
  Module plone.z3cform.layout, line 54, in update
  Module plone.dexterity.browser.edit, line 52, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 138, in update
  Module z3c.form.action, line 99, in execute
  Module z3c.form.button, line 315, in **call**
  Module z3c.form.button, line 170, in **call**
  Module plone.dexterity.browser.edit, line 27, in handleApply
  Module z3c.form.group, line 119, in applyChanges
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module plone.app.versioningbehavior.subscribers, line 63, in create_version_on_save
  Module Products.CMFEditions.CopyModifyMergeRepositoryTool, line 299, in save
  Module Products.CMFEditions.CopyModifyMergeRepositoryTool, line 445, in _recursiveSave
  Module Products.CMFEditions.ArchivistTool, line 267, in prepare
  Module Products.CMFEditions.ArchivistTool, line 221, in _cloneByPickle
TypeError: Can't pickle objects in acquisition wrappers.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=249_

**Comment by jensens** [comment]
outdated
