### ISSUE TITLE
Preview not available from history view with versioning enabled

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#58]
_Original author: anthonyg...@gmail.com (March 21, 2012 19:26:52)_

<b>What steps will reproduce the problem?</b>
1. set-up a content type with plone.app.versioningbehavior.behaviors.IVersionable behaviour
2. create an item of that content type
3. make a few edits
4. click &quot;history&quot;
5. click &quot;preview&quot; for one of the old versions on the history menu 

<b>What is the expected output? What do you see instead?</b>
Expected: see that version of the item rendered with its default template
Actual: &quot;preview not available&quot;

<b>What version of the product are you using? On what operating system?</b>
Dexterity 1.2, Plone 4.1.4

<b>Please provide any additional information below.</b>
Versioning is a bit pointless without the ability to do all of these:
- view previous versions
- view changes introduced in a version (some kind of diff view)
- revert to a preview version

Currently we only have the last one

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=261_

**Comment by jensens** [comment]
outdated
