### ISSUE TITLE
Support for adding dexterity fields should the searchable text index should be part of p.a.dexterity

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#59]
_Original author: anthonyg...@gmail.com (March 23, 2012 11:22:30)_

This is essentially a feature request for adding the functionality of collective.dexteritytextindexer to p.a.dexterity.

Requirements are to be able to add a field to the SearchableText index:
- in a behavior interface by using a directive like searchable('my_field')
- in a model xml by doing something like indexer:searchable=&quot;true&quot;
- TTW

Currently collective.dexteritytextindexer does the first two

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=262_

**Comment by petschki** [comment]
outdated
