### ISSUE TITLE
Default RelationList widget does not show absolute_url for virtualhost mapped sites

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#60]
_Original author: khairil....@gmail.com (March 26, 2012 08:12:15)_

<b>What steps will reproduce the problem?</b>
1. Use Plone site with virtualhost mapping
2. Use a RelationList to link to dexterity content type
3. Click on the link on that field with the default generated view

<b>What is the expected output? What do you see instead?</b>

Expected /folder/content

Get /Plone/folder/content link instead

<b>What version of the product are you using? On what operating system?</b>

plone.app.dexterity-1.2.1 Linux/FreeBSD

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=263_

**Comment by jensens** [comment]
outdated
