### ISSUE TITLE
Contenttree widget display form links not correct

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#62]
_Original author: frank...@fourdigits.nl (March 28, 2012 06:35:48)_

I use a relationlist in one of my types with a custom navigation_tree_query, this is the field:

   leden = RelationList(
            title=_(u&quot;leden&quot;),
            default=[],
            value_type=RelationChoice(
                    title=_(u&quot;Related&quot;),
                    source=ObjPathSourceBinder( \
                        navigation_tree_query={
                          'portal_type':
                          ['lid',
                           'landelijk',
                           'afdeling',
                           'vereniging',
                           'dexteritycontenttypes.folder'],
                      'path': {'query': '/Site/myfolder'}},
                  portal_type='lid'
                  ),
            ),
            required=False,
        )

This works wonderful in edit mode, it starts at the correct folder set in path and browse into the contenttypes set in the navigation_tree_query and select only 'lid' contenttypes. 

But in displayview it renders the wrong links

plone.formwidget.contenttree/display_{single,multiple}.pt  use term token which looks like a brain.getPath() results, which includes the plonesite in the path 

(Pdb) results[0].getPath()
'/Site/my_folder/202/1983/36336'
(Pdb) results[0].getURL()
'http://dev.local/myfolder/202/1983/36336'

In my case I solved by an override template for the display template, I used term/value/absolute_url_path instead of term/token, which does the job here, but I don't know whether this is a real solution.

display_multiple.pt
...
   &lt;div tal:repeat=&quot;term view/terms&quot;&gt;
        &lt;a tal:content=&quot;term/title&quot;
           tal:attributes=&quot;href term/value/absolute_url_path&quot;
           tal:condition=&quot;python:not(term.token.startswith('#error-'))&quot;
           /&gt;
    &lt;/div&gt;

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=266_

**Comment by jensens** [comment]
outdated
