### ISSUE TITLE
protect core Dexterity types from being edited by non-Managers

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#67]
_Original author: racials...@gmail.com (June 04, 2012 21:35:19)_

As per a discussion on plone-developers between Kim Nguyen and David Glick (see below), a strength of the PloneFormGen + uwosh.pfg.d2c way of creating content types is that normal users (who have been granted the permission to create or edit PFG forms) can create their own content types.  This is currently not the case with Dexterity. The Dexterity types panel uses &quot;Manage schemata&quot;, which could be granted to non-Manager users, but those users should not be allowed to edit core Dexterity types or other users' Dexterity types.

T. Kim Nguyen       3:22 PM (1 hour ago)
Just putting my &quot;regler ol' user&quot; hat on again, I know a big big plus for Dex...

David Glick (GW) davidglick@groundwire.org
3:30 PM (1 hour ago)

to me, plone-develope. 
On Jun 4, 2012, at 1:22 PM, T. Kim Nguyen wrote:

&gt; Just putting my &quot;regler ol' user&quot; hat on again, I know a big big plus for Dexterity is that one can create content types TTW the way we currently use PloneFormGen and D2C, with the exception that (as I understand it) to get to the Dexterity control panel one needs Manager role, correct?  If I'm going to want to let my power users loose creating new content types, it's ok to give them Manager on a small development site, but not so good on a large production site.  In the latter case, PFG + D2C is more suitable.  I guess my question is: is there a way now or will there be in the future for non-Manager users to create new Dexterity types TTW?
&gt;

The Dexterity control panel is protected by a &quot;Manage schemata&quot; permission. It defaults to Managers only, but you can easily assign it to other roles.  In fact I should probably change it to include Site Administrators by default.

T. Kim Nguyen
3:34 PM (57 minutes ago)

to David, plone-develope. 
Awesome!

Detailed question though: if non-Managers are assigned that permission, does it mean they can mess with core Dexterity types, or is there a way to distinguish between core types and per-user custom/new types?  With PFG one can obviously grant any individual the permission to create and edit a form without having that affect any other forms (and D2C content types) on the site.

David Glick (GW) davidglick@groundwire.org
3:47 PM (44 minutes ago)

to me, plone-develope. 
On Jun 4, 2012, at 1:34 PM, T. Kim Nguyen wrote:

&gt; Awesome!
&gt;
&gt; Detailed question though: if non-Managers are assigned that permission, does it mean they can mess with core Dexterity types, or is there a way to distinguish between core types and per-user custom/new types?  With PFG one can obviously grant any individual the permission to create and edit a form without having that affect any other forms (and D2C content types) on the site.
&gt;

It's not per-type at this point. That's a good idea and probably wouldn't be too hard to implement.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=271_

**Comment by fulv** [comment]
Right now, in Plone 5.2, in `plone/app/dexterity/profiles/default/controlpanel.xml`, the `@@dexterity-types` control panel has permission **Manage portal** and not **Manage schemata**.
