### ISSUE TITLE
Dexterity Behaviors-form allows to select behaviors not really available for the current type

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#69]
_Original author: dataku...@gmail.com (September 19, 2012 09:20:54)_

<b>What steps will reproduce the problem?</b>
1. Register a new behavior for your custom type only with
   &lt;plone:behavior ... for=&quot;my.app.schema.IMyType&quot; /&gt;
2. Go to edit behaviors (TTW) for some other Dexterity content type.
3. You are allowed to select also the behavior registered in 1).
4. Viewing or editing any content of the type in 3) will fail, because there's no adapter registered for that behavior for that type (because of for-paraameter in 1).

<b>What is the expected output? What do you see instead?</b>

I'd expect the TTW behaviors form to hide behaviors, which are not registered for the currently edited content type.

<b>What version of the product are you using? On what operating system?</b>

plone.app.dexterity = 1.2.1

But the behaviors form seem to still just give all the available behaviors in https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/browser/behaviors.py#L64

-Asko

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=276_

**Comment by jensens** [comment]
outdated
