### ISSUE TITLE
RelationChoice/RelationList content-tree popup not working Plone 4.2

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#72]
_Original author: zopyxfilter (December 04, 2012 06:54:59)_

We moved a Dexterity based application using a RelationChoice/RelationList from Plone 4.1 to Plone 4.2 (while upgrading from Dexterity 1.2 to 2.0). The content-tree popup window does no longer seem to work. I don't encounter any JS errors....so no idea what's going on here.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=281_

**Comment by jensens** [comment]
outdated
