### ISSUE TITLE
Should copied objects use INameChooser?

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#73]
_Original author: wich...@wiggy.net (January 10, 2013 10:44:32)_

Currently when copying a dexterity object the new id is determine by the OFS.CopySupport.CopySupport._get_id() method, which returns a copyN_of_&lt;original id&gt;. This may create names that violation the naming policy as defined by the INameChooser adapter.

Should dexterity override _get_item to defer to the name chooser?

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=282_

**Comment by pbauer** [comment]
fixed in https://github.com/plone/plone.app.content/commit/498634
