### ISSUE TITLE
Tests failing on p.a.versioningbehavior/stagingbehavior

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.dexterity#74]
_Original author: m...@rpatterson.net (February 08, 2013 23:49:05)_

With current buildout.coredev some tests in these two packages fail:

Running tests at level 1
Running Products.PloneTestCase.layer.PloneSite tests:
  Set up Testing.ZopeTestCase.layer.ZopeLite in 0.672 seconds.
  Set up Products.PloneTestCase.layer.ZCML in 2.528 seconds.
  Set up Products.PloneTestCase.layer.PloneSite in 3.654 seconds.

Failure in test /opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt
Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/unittest/case.py&quot;, line 327, in run
    testMethod()
  File &quot;/usr/lib/python2.7/doctest.py&quot;, line 2201, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for doctest_behavior.txt
  File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 0

---

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 51, in doctest_behavior.txt
Failed example:
    browser.getControl(name='form.widgets.title').value = 'Blubb'
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[21]&gt;&quot;, line 1, in &lt;module&gt;
        browser.getControl(name='form.widgets.title').value = 'Blubb'
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 371, in getControl
        control, form = disambiguate(intermediate, msg, index)
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 48, in disambiguate
        raise LookupError(msg)
##     LookupError: name 'form.widgets.title'

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 75, in doctest_behavior.txt
Failed example:
    browser.getControl(name='form.widgets.title').value = 'Blubb2'
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[30]&gt;&quot;, line 1, in &lt;module&gt;
        browser.getControl(name='form.widgets.title').value = 'Blubb2'
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 371, in getControl
        control, form = disambiguate(intermediate, msg, index)
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 48, in disambiguate
        raise LookupError(msg)
##     LookupError: name 'form.widgets.title'

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 102, in doctest_behavior.txt
Failed example:
    browser.getControl(name='form.widgets.title').value = 'Init test'
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[42]&gt;&quot;, line 1, in &lt;module&gt;
        browser.getControl(name='form.widgets.title').value = 'Init test'
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 371, in getControl
        control, form = disambiguate(intermediate, msg, index)
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 48, in disambiguate
        raise LookupError(msg)
##     LookupError: name 'form.widgets.title'

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 129, in doctest_behavior.txt
Failed example:
    browser.getControl(name='paths:list').displayValue = ['Blubb2']
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in **run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[53]&gt;&quot;, line 1, in &lt;module&gt;
        browser.getControl(name='paths:list').displayValue = ['Blubb2']
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 97, in __setattr**
        object.**setattr**(self, name, value)
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 572, in fset
        self.mech_control.set_value_by_label(value)
      File &quot;/opt/src/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_form.py&quot;, line 2092, in set_value_by_label
        raise ItemNotFoundError(nn)
##     ItemNotFoundError: Blubb2

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 131, in doctest_behavior.txt
Failed example:
    browser.getControl(name='folder_paste:method').click()
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[55]&gt;&quot;, line 1, in &lt;module&gt;
        browser.getControl(name='folder_paste:method').click()
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 371, in getControl
        control, form = disambiguate(intermediate, msg, index)
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 48, in disambiguate
        raise LookupError(msg)
##     LookupError: name 'folder_paste:method'

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 132, in doctest_behavior.txt
Failed example:
    'copy_of_testingtype' in self.portal.objectIds()
Differences (ndiff with -expected +actual):
    - True
##     + False

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 138, in doctest_behavior.txt
Failed example:
    browser.open('http://nohost/plone/copy_of_testingtype/edit')
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[57]&gt;&quot;, line 1, in &lt;module&gt;
        browser.open('http://nohost/plone/copy_of_testingtype/edit')
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 240, in open
        self.mech_browser.open(url, data)
      File &quot;/opt/src/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py&quot;, line 203, in open
        return self._mech_open(url, data, timeout=timeout)
      File &quot;/opt/src/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py&quot;, line 230, in _mech_open
        response = UserAgentBase.open(self, request, data)
      File &quot;/opt/src/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_opener.py&quot;, line 193, in open
        response = urlopen(self, req, data)
      File &quot;/opt/src/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_urllib2_fork.py&quot;, line 344, in _open
        '_open', req)
      File &quot;/opt/src/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_urllib2_fork.py&quot;, line 332, in _call_chain
        result = func(_args)
      File &quot;/opt/src/eggs/Zope2-2.13.19-py2.7.egg/Testing/testbrowser.py&quot;, line 83, in http_open
        return self.do_open(PublisherConnection, req)
      File &quot;/usr/lib/python2.7/urllib2.py&quot;, line 1174, in do_open
        h.request(req.get_method(), req.get_selector(), req.data, headers)
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/testing.py&quot;, line 76, in request
        self.response = self.caller(request_string, handle_errors)
      File &quot;/opt/src/eggs/Zope2-2.13.19-py2.7.egg/Testing/ZopeTestCase/functional.py&quot;, line 38, in wrapped_func
        return func(_args, **kw)
      File &quot;/opt/src/eggs/Zope2-2.13.19-py2.7.egg/Testing/ZopeTestCase/zopedoctest/functional.py&quot;, line 186, in http
        debug=not handle_errors,
      File &quot;/opt/src/eggs/Zope2-2.13.19-py2.7.egg/ZPublisher/Publish.py&quot;, line 443, in publish_module
        environ, debug, request, response)
      File &quot;/opt/src/eggs/Zope2-2.13.19-py2.7.egg/ZPublisher/Publish.py&quot;, line 237, in publish_module_standard
        response = publish(request, module_name, after_list, debug=debug)
      File &quot;/opt/src/eggs/Zope2-2.13.19-py2.7.egg/ZPublisher/Publish.py&quot;, line 115, in publish
        object=request.traverse(path, validated_hook=validated_hook)
      File &quot;/opt/src/eggs/Zope2-2.13.19-py2.7.egg/ZPublisher/BaseRequest.py&quot;, line 518, in traverse
        return response.notFoundError(URL)
      File &quot;/opt/src/eggs/Zope2-2.13.19-py2.7.egg/ZPublisher/HTTPResponse.py&quot;, line 718, in notFoundError
        &quot;&lt;p&gt;&lt;b&gt;Resource:&lt;/b&gt; &#37;s&lt;/p&gt;&quot; &#37; escape(entry))
    NotFound:   &lt;h2&gt;Site Error&lt;/h2&gt;
      &lt;p&gt;An error was encountered while publishing this resource.
      &lt;/p&gt;
      &lt;p&gt;&lt;strong&gt;Resource not found&lt;/strong&gt;&lt;/p&gt;

```
  Sorry, the requested resource does not exist.&lt;p&gt;Check the URL and try again.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Resource:&lt;/b&gt; http://nohost/plone/copy_of_testingtype&lt;/p&gt;
  &lt;hr noshade=&quot;noshade&quot;/&gt;

  &lt;p&gt;Troubleshooting Suggestions&lt;/p&gt;

  &lt;ul&gt;
  &lt;li&gt;The URL may be incorrect.&lt;/li&gt;
  &lt;li&gt;The parameters passed to this resource may be incorrect.&lt;/li&gt;
  &lt;li&gt;A resource that this resource relies on may be
      encountering an error.&lt;/li&gt;
  &lt;/ul&gt;

  &lt;p&gt;For more detailed information about the error, please
  refer to the error log.
  &lt;/p&gt;

  &lt;p&gt;If the error persists please contact the site maintainer.
  Thank you for your patience.
  &lt;/p&gt;
```

---

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 139, in doctest_behavior.txt
Failed example:
    browser.getControl(name='form.widgets.title').value = 'Dup'
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[58]&gt;&quot;, line 1, in &lt;module&gt;
        browser.getControl(name='form.widgets.title').value = 'Dup'
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 370, in getControl
        label, name, self.mech_browser.forms(), include_subcontrols=True)
      File &quot;/opt/src/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py&quot;, line 418, in forms
        if not self.viewing_html():
      File &quot;/opt/src/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py&quot;, line 443, in viewing_html
        raise BrowserStateError(&quot;not viewing any document&quot;)
##     BrowserStateError: not viewing any document

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 140, in doctest_behavior.txt
Failed example:
    field = browser.getControl(name='form.widgets.IVersionable.changeNote')
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[59]&gt;&quot;, line 1, in &lt;module&gt;
        field = browser.getControl(name='form.widgets.IVersionable.changeNote')
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 370, in getControl
        label, name, self.mech_browser.forms(), include_subcontrols=True)
      File &quot;/opt/src/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py&quot;, line 418, in forms
        if not self.viewing_html():
      File &quot;/opt/src/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py&quot;, line 443, in viewing_html
        raise BrowserStateError(&quot;not viewing any document&quot;)
##     BrowserStateError: not viewing any document

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 141, in doctest_behavior.txt
Failed example:
    field.value = 'Edited the duplicate'
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in **run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[60]&gt;&quot;, line 1, in &lt;module&gt;
        field.value = 'Edited the duplicate'
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 97, in __setattr**
        object.**setattr**(self, name, value)
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 527, in fset
        raise zope.testbrowser.interfaces.ExpiredError
##     ExpiredError

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 142, in doctest_behavior.txt
Failed example:
    browser.getControl(name='form.buttons.save').click()
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[61]&gt;&quot;, line 1, in &lt;module&gt;
        browser.getControl(name='form.buttons.save').click()
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 370, in getControl
        label, name, self.mech_browser.forms(), include_subcontrols=True)
      File &quot;/opt/src/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py&quot;, line 418, in forms
        if not self.viewing_html():
      File &quot;/opt/src/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py&quot;, line 443, in viewing_html
        raise BrowserStateError(&quot;not viewing any document&quot;)
##     BrowserStateError: not viewing any document

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 143, in doctest_behavior.txt
Failed example:
    browser.url
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[62]&gt;&quot;, line 1, in &lt;module&gt;
        browser.url
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 177, in url
        return self.mech_browser.geturl()
      File &quot;/opt/src/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py&quot;, line 334, in geturl
        raise BrowserStateError(&quot;not viewing any document&quot;)
##     BrowserStateError: not viewing any document

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 166, in doctest_behavior.txt
Failed example:
    browser.getControl(name='form.widgets.title').value = 'MyFolder'
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[67]&gt;&quot;, line 1, in &lt;module&gt;
        browser.getControl(name='form.widgets.title').value = 'MyFolder'
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 371, in getControl
        control, form = disambiguate(intermediate, msg, index)
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 48, in disambiguate
        raise LookupError(msg)
##     LookupError: name 'form.widgets.title'

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 167, in doctest_behavior.txt
Failed example:
    browser.getControl(name='form.widgets.description').value = 'MyFolder'
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[68]&gt;&quot;, line 1, in &lt;module&gt;
        browser.getControl(name='form.widgets.description').value = 'MyFolder'
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 371, in getControl
        control, form = disambiguate(intermediate, msg, index)
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 48, in disambiguate
        raise LookupError(msg)
##     LookupError: name 'form.widgets.description'

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 176, in doctest_behavior.txt
Failed example:
    browser.getControl(name='form.widgets.title').value = 'My versioned object'
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[72]&gt;&quot;, line 1, in &lt;module&gt;
        browser.getControl(name='form.widgets.title').value = 'My versioned object'
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 371, in getControl
        control, form = disambiguate(intermediate, msg, index)
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 48, in disambiguate
        raise LookupError(msg)
##     LookupError: name 'form.widgets.title'

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 177, in doctest_behavior.txt
Failed example:
    browser.getControl(name='form.widgets.description').value = 'The Description'
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[73]&gt;&quot;, line 1, in &lt;module&gt;
        browser.getControl(name='form.widgets.description').value = 'The Description'
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 371, in getControl
        control, form = disambiguate(intermediate, msg, index)
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 48, in disambiguate
        raise LookupError(msg)
##     LookupError: name 'form.widgets.description'

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 228, in doctest_behavior.txt
Failed example:
    browser.getControl(name='form.widgets.title').value = 'Versioned container one'
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[94]&gt;&quot;, line 1, in &lt;module&gt;
        browser.getControl(name='form.widgets.title').value = 'Versioned container one'
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 371, in getControl
        control, form = disambiguate(intermediate, msg, index)
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 48, in disambiguate
        raise LookupError(msg)
##     LookupError: name 'form.widgets.title'

File &quot;/opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt&quot;, line 258, in doctest_behavior.txt
Failed example:
    browser.getControl(name='form.widgets.title').value = 'Versioned container two'
Exception raised:
    Traceback (most recent call last):
      File &quot;/usr/lib/python2.7/doctest.py&quot;, line 1289, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest doctest_behavior.txt[108]&gt;&quot;, line 1, in &lt;module&gt;
        browser.getControl(name='form.widgets.title').value = 'Versioned container two'
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 371, in getControl
        control, form = disambiguate(intermediate, msg, index)
      File &quot;/opt/src/eggs/zope.testbrowser-3.11.1-py2.7.egg/zope/testbrowser/browser.py&quot;, line 48, in disambiguate
        raise LookupError(msg)
    LookupError: name 'form.widgets.title'

  Ran 33 tests with 1 failures and 0 errors in 10.869 seconds.
Running plone.app.stagingbehavior.tests.base.plone.app.stagingbehavior:Functional tests:
  Tear down Products.PloneTestCase.layer.PloneSite in 0.110 seconds.
  Tear down Products.PloneTestCase.layer.ZCML in 0.006 seconds.
  Tear down Testing.ZopeTestCase.layer.ZopeLite in 0.000 seconds.
  Set up plone.testing.zca.LayerCleanup in 0.001 seconds.
  Set up plone.testing.z2.Startup in 0.062 seconds.
  Set up plone.app.testing.layers.PloneFixture in 3.464 seconds.
  Set up plone.app.stagingbehavior.tests.base.Fixture/opt/src/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/fields.py:417: UserWarning: You did not specify an i18n translation domain for the 'description' field in /opt/src/buildout.coredev/src/plone.app.stagingbehavior/plone/app/stagingbehavior/configure.zcml
  &quot;'&#37;s' field in &#37;s&quot; &#37; (self.getName(), context.info.file )
/opt/src/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/fields.py:417: UserWarning: You did not specify an i18n translation domain for the 'title' field in /opt/src/buildout.coredev/src/plone.app.stagingbehavior/plone/app/stagingbehavior/configure.zcml
  &quot;'&#37;s' field in &#37;s&quot; &#37; (self.getName(), context.info.file )
 in 1.304 seconds.
  Set up plone.app.stagingbehavior.tests.base.plone.app.stagingbehavior:Functional in 0.000 seconds.

Failure in test /opt/src/buildout.coredev/src/plone.app.stagingbehavior/plone/app/stagingbehavior/tests/regressiontests.txt
Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/unittest/case.py&quot;, line 327, in run
    testMethod()
  File &quot;/usr/lib/python2.7/doctest.py&quot;, line 2201, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for regressiontests.txt
  File &quot;/opt/src/buildout.coredev/src/plone.app.stagingbehavior/plone/app/stagingbehavior/tests/regressiontests.txt&quot;, line 0

---

File &quot;/opt/src/buildout.coredev/src/plone.app.stagingbehavior/plone/app/stagingbehavior/tests/regressiontests.txt&quot;, line 29, in regressiontests.txt
Failed example:
    browser.url
Expected:
    'http://nohost/plone/test_folder/view'
Got:
##     'http://nohost/plone/test_folder-1/view'

File &quot;/opt/src/buildout.coredev/src/plone.app.stagingbehavior/plone/app/stagingbehavior/tests/regressiontests.txt&quot;, line 39, in regressiontests.txt
Failed example:
    browser.url
Expected:
    'http://nohost/plone/test_folder/stageable_type/view'
Got:
##     'http://nohost/plone/test_folder/stageable_type-2/view'

File &quot;/opt/src/buildout.coredev/src/plone.app.stagingbehavior/plone/app/stagingbehavior/tests/regressiontests.txt&quot;, line 54, in regressiontests.txt
Failed example:
    browser.url
Expected:
    'http://nohost/plone/test_folder/stageable_type'
Got:
    'http://nohost/plone/test_folder/stageable_type-2'

  Ran 2 tests with 1 failures and 0 errors in 4.575 seconds.
Running plone.app.stagingbehavior.tests.base.plone.app.stagingbehavior:Integration tests:
  Tear down plone.app.stagingbehavior.tests.base.plone.app.stagingbehavior:Functional in 0.000 seconds.
  Set up plone.app.stagingbehavior.tests.base.plone.app.stagingbehavior:Integration in 0.000 seconds.
  Ran 6 tests with 0 failures and 0 errors in 1.084 seconds.
Tearing down left over layers:
  Tear down plone.app.stagingbehavior.tests.base.plone.app.stagingbehavior:Integration in 0.000 seconds.
  Tear down plone.app.stagingbehavior.tests.base.Fixture in 0.004 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.041 seconds.
  Tear down plone.testing.z2.Startup in 0.003 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.005 seconds.

Tests with failures:
   /opt/src/buildout.coredev/src/plone.app.versioningbehavior/plone/app/versioningbehavior/tests/doctest_behavior.txt
   /opt/src/buildout.coredev/src/plone.app.stagingbehavior/plone/app/stagingbehavior/tests/regressiontests.txt

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=284_

**Comment by jensens** [comment]
outdated
